package org.example.model.enums;

public enum Status {
    START,

    WAITING_FOR_LANGUAGE_SELECTION,

    USER_PANEL,

    WAITING_FOR_CHANNEL_VERIFICATION,

    WAITING_FOR_AD_TEXT,
    WAITING_FOR_AD_PRICE,
    WAITING_FOR_AD_LOCATION,
    WAITING_FOR_AD_DESCRIPTION,
    WAITING_FOR_AD_PHOTO,
    WAITING_FOR_AD_CONTACT,
    WAITING_FOR_AD_CONFIRMATION,

    WAITING_FOR_MEDIA,

    WAITING_FOR_CONFIRMATION,

    SENDING_AD,

    FINISHED,

    CANCELLED,

    UNKNOWN,

    WAITING_FOR_SCHEDULE_TIME,

    WAITING_FOR_PAYMENT,

    ADMIN_PANEL
}
